project:
  type: website

website:
  site-url: https://pages.narang99.in  # you must change this appropriately for RSS feeds to work properly
  title: "Hariom Narang's Pages"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/narang99
format:
  html:
    respect-user-color-scheme: true
    toc: true
    css:
      - styles.css
    mathjax: true
    include-in-header: 
      - text: |
          <script data-goatcounter="https://narang99.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    theme:
      light: cosmo
      dark: cyborg