---
title: The jump from discrete to continuous probability
author: Hariom Narang
description: Understanding how the intuition of discrete probability maps to probability distribution functions
categories: [Math]
date: 'May 17, 2026'
---

Whenever we start learning about probability theory, we start with discrete probability. This is a good start—an easy start. The questions posed in discrete probabilities are also very simple and intuitive. It becomes slightly confusing when we move to the continuous case, and I feel there is a lot of material that we assume is obvious but doesn't really make sense. I'm going to talk about what helped me understand the link between the discrete and the continuous case.    

# A simple discrete case problem

Let's consider a simple example of a bag containing apples and oranges. You are asked "what is the probability of drawing an apple on a random draw?"  

Many of us would start by asking how many apples and oranges are present in the bag when we are asked to measure the probability of randomly picking an apple. This is a slightly bad way to think about it.  
Many math textbooks are very strict about the phrasing, though. They start with the question: "You have a bag containing apples and oranges. You pick a single fruit on a random draw and put it back inside the bag. Each time, you keep a count of the number of apples and oranges drawn, and you keep track of the ratio of the number of apples to the total fruits. You do not know how many apples and oranges are present, but you do the experiment many times."  

The theory says that as the number of draws goes toward infinity, the ratio tends toward the actual ratio of apples/total fruits (and the same thing for oranges) in the bag.   


::: {.callout-tip}
The key is to keep saying "I'm going to draw an object randomly". This will come in handy later in maintaining a sane intuition about working with probability.  
:::


# Bayesian rule with a simple discrete example

The example is taken from the [PRML book](https://www.amazon.in/Pattern-Recognition-Machine-Learning-2009/dp/1493938436) as is, as I want to actually talk about how the thinking shifts from discrete to the continuous case mainly.  
Consider two random variables $X$ and $Y$. $X$ can take values $x_0, x_1, ... x_M$ and $Y$ can take values $y_0, y_1, ... y_L$. In our draw, imagine that we are drawing a ball from a bag again. Each ball has two labels: the $X$ label and the $Y$ label. We say we drew $x_i, y_j$ if the ball has these two as labels.  
The trial is done, and we are given the results that the number of times we pick a ball containing the label $x_i, y_j$ is $n_{ij}$. The total number of experiments is $N$.  

We say the probability of drawing the ball containing labels $x_i, y_j$ is $P(X=i, Y=j) = n_{ij} / N$. Simple.   
I'll now discuss the basic rules of manipulating probabilities, they are quite intuitive in the discrete case.   

## Sum rule

What is the probability of finding balls that contain the label $x_i$, irrespective of the $y$ label on that ball? It is the sum of all balls containing the label $x_i$ divided by $N$.  

$$P(X=x_i) = \sum_{j=0}^{L} (n_{ij}) / N = \sum_{j=0}^{L} P(X=x_i, Y=y_j)$$

That's the sum rule—simple. The above expression is also called marginalizing over $Y$. I don't know what the word means, but we are basically summing over all values of $Y$.  

## Conditional Probabilities

Let's consider the probability of finding that the ball has label $x_i$ given that the drawn ball has label $y_j$. This is denoted by $P(X=x_i | Y=y_j)$ (probability of drawing $X=x_i$ given $Y=y_j$).  

This is basically the number of balls containing the labels $x_i, y_j$ divided by the total number of balls containing the label $y_j$.  


We get the denominator using the sum rule by marginalizing over $X$. We multiply and divide by $N$ to convert each component into the probability.  

$$
\begin{align}
P(X=x_i | Y=y_j) &= \frac{n_{ij}}{\sum_{i=0}^{M} n_{ij}} \\
&= \frac{n_{ij}}{N} \frac{N}{\sum_{i=0}^{M} n_{ij}} \\
&= \frac{P(X=x_i, Y=y_j)}{\sum_{i=0}^{M} P(X=x_i, Y=y_j)} \\
&= \frac{P(X=x_i, Y=y_j)}{P(Y=y_j)} \\
P(X=x_i | Y=y_j)P(Y=y_j) &= P(X=x_i, Y=y_j) \\
\end{align}
$$

---

Since $P(X=x_i, Y=y_j) = P(Y=y_j, X=x_i)$, we get the Bayesian rule
$$
\begin{align}
P(X=x_i | Y=y_j)P(Y=y_j) &= P(Y=y_j | X=x_i )P(X=x_i) \\
P(X|Y)P(Y) &= P(Y|X)P(X)
\end{align}
$$

People simply abbreviate $P(X=x_i)$ to $P(X)$; we have to get used to it.  

# Towards continuous variables

Let's say $X$ is a continuous variable. You can imagine it as a bag containing infinite numbers—you draw something and each time you get a new number.  

In the discrete case of fruits, we get two kinds of objects, apple and orange, in our experiment.  
Here, we get numbers. Each number is different. Imagine you have a bag containing infinite types of distinct apples. That is the first distinction you should make.  

A classical historical example comes from when Gauss wanted to understand how errors in measurement behaved in nature. You can imagine him thinking that he was given a bag containing a bunch of numbers, each number an error margin in the measurement. Crucially, each error number is different—as different as an orange and an apple in our discrete case.   

Suddenly, though, every textbook starts talking about a "probability density function" or PDF. And they say it's not the same as probability. In the continuous case, it is impossible to assign a probability to a single number because there are an infinite number of numbers, so the probability sums then become infinite. So they assign probability to a range of values.  

$$
p(x \in (a,b)) = \int_{a}^{b} PDF(x) \,dx
$$

We are now supposed to talk in ranges. I can get back to understanding how papers use continuous probabilities. Wrong. Papers throw the words PDF and probabilities interchangeably. My simple mind is still stuck at apples and oranges ;_;  

They even have a counterpart of the Bayesian rule
$$
PDF(x|y)PDF(x) = PDF(y|x)PDF(x)
$$


How you can go from $P(x|y)P(x) = P(y|x)P(x)$ to the formula above is not obvious at all.  

We are now talking about probability density functions as if they were probabilities themselves.  

Technically, this expands to integrals. Let's go with expanding $P(x|y) = P(x,y) / P(y)$.  
$$
P(x \in (a,b) | y \in (c,d)) = \frac{\int_{c}^{d} \int_{a}^{b} p(x,y) \,dx \,dy}{\int_{c}^{d} p_Y(y) \,dy}
$$

The most confusing thing now is that everyone talks about PDFs generally (which is written as $p$ in the continuous case) in the same way as the $P$ in the discrete case (or at least they sound like that; the similarity in the intuition of using both is uncanny). Nobody talks about the integral much (other than saying "the integral sums up to 1, not the density function").  

## Deriving product rule
The actual rigorous derivation starts from the integral above. I haven't read it; the prerequisite to understand it is to understand measure theory, which I'm not familiar with.  

There is a simpler, informal proof that is given, which I'm providing here.  

You simply consider the probability for an infinitesimally small area where $X \in \delta x$ and $Y \in \delta y$. In this case, some of the integrals disappear.  

$$
\begin{align}
P(Y \in [y_0, y_0+\delta y] \mid X \in [x_0, x_0+\delta x]) &= \frac{P(X \in [x_0, x_0+\delta x],\ Y \in [y_0, y_0+\delta y])}{P(X \in [x_0, x_0+\delta x])} \\
&= \frac{\displaystyle\int_{x_0}^{x_0+\delta x}\int_{y_0}^{y_0+\delta y} p(x,y)\, dy\, dx}{\displaystyle\int_{x_0}^{x_0+\delta x} p_X(x)\, dx} \\
&= \frac{p(x,y) \delta x \delta y}{p_X(x) \delta x} \\
P(Y|X) &= \frac{p(x,y)}{p_X(x)} \delta y
\end{align}
$$

We took the limit as $\delta x, \delta y \to 0$; the integral goes away. Now, $P(Y|X)$ of the form $f \cdot \delta y$, we can say $f$ is the PDF of $P(Y|X)$.  


$$p(Y|X) = \frac{p(x,y)}{p_X(x)}$$

And it seems PDFs behave the same way as the discrete counterparts do.  

# Intuition

What helps me is this: Consider the difference between counting and measuring a distance. When we count the number of apples, we just say "1 apple," "2 apples," and so on. This is the discrete case. For measuring distance, we say "1 km," "2 km," and so on. The distance measurement can be "counted" if we use a range for defining some unit measurement.  

That $\delta x$ is this range. It helps move all our intuition about counting in the discrete case to the continuous case. Since the PDFs behave approximately the same way as discrete probabilities in the core sum and product rules, we can reason about them similarly.  

Another way to think about it is that in the discrete case, we are really talking about the probability distribution function only. It's just that the range is $1$, and so we can handwave it as the actual probability of the event.  


# Multiple dimensions

Now a random variable $X$ can be a random variable of vectors. In this case, our bag contains points in an $N$-dimensional space. Everything else is reasonably the same. If we have two random variables $X$ and $Y$ in $N$ dimensions, imagine picking a ball with 2 labels (as in the single-dimension case). The labels are themselves, however, vectors.  

Now people generally talk about covariance matrices. These contain elements for denoting the covariance between the dimensions $X_i$ and $Y_j$. The sampling strategy is different now, though. This covariance matrix only makes sense if you think that the bag contains balls and each ball has a label for each dimension of $X$ and $Y$. Each dimension is a separate random variable. It really is just a 1D concept, then, decorated as a matrix to make it concise. If the number of dimensions is $N$, the covariance defines the covariance between $2N$ random variables (1 for each dimension of $X$, 1 for each dimension of $Y$).  

This is why I said before that the language of saying "I'm picking from a bag containing balls with numbers as labels many times" is more useful to reason about probability than saying "What are the ratios of the numbers inside the bag?" In the end, we still use probability distribution functions, which directly give us the answer, but it is still useful to think of it this way for me.  

Imagining a ball with "distinct labels" lets us reason about which random variables are coming together (the set of labels we get from a single draw of a ball).  